# Generated by Django 4.2.8 on 2024-01-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('picture_url', models.URLField(max_length=250)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannels', to='contents.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('genre', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('file_url', models.URLField(max_length=250)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='contents.channel')),
            ],
        ),
    ]
