# Generated by Django 4.2.8 on 2024-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
