# Generated by Django 4.2.8 on 2024-01-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_channel_parent_alter_content_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.channel'),
        ),
    ]
