# Generated by Django 4.2.8 on 2024-01-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_channel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
