# Generated by Django 4.2.8 on 2024-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_channel_slug_alter_channel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=250), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=250), max_length=250, unique=True),
        ),
    ]
