# Generated by Django 4.2.8 on 2024-01-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_content_active_alter_channel_slug_alter_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='parent',
        ),
        migrations.AddField(
            model_name='channel',
            name='superchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subchannel', to='contents.channel'),
        ),
    ]
