# Generated by Django 4.2.8 on 2024-02-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_channel_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='created_by',
        ),
    ]
