# Generated by Django 4.2.8 on 2024-02-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_remove_channel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
