# Generated by Django 4.2.8 on 2024-02-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_content_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
        migrations.RemoveField(
            model_name='content',
            name='genre',
        ),
    ]
