name: Popflix CI

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-latest
    env: 
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - uses: actions/checkout@v2

      - name: docker_image
        run: docker build -t popflix . --file Dockerfile

      - name: docker_container
        run: docker-compose up -d

      - name: run_tests
        run: |
          docker-compose exec -t web python manage.py test